version: "3"

services:
  app:
    build:
        context: .
        dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www/
    depends_on:
        - db
    container_name: api-data-download_app

  db:
      image: mysql:8.2
      restart: always
      volumes:
          - ./tmp/db:/var/lib/mysql
      environment:
          MYSQL_DATABASE: api-data-download
          MYSQL_ROOT_PASSWORD: root
      ports:
          - 8101:1234
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      container_name: api-data-download_db
